---- loading plugins through packer(plugins.lua)
-- require('config.lazy')
require("config.pack")
require("config.options")
require("config.autocmds")
require("config.mappings")
-- require("config.colors")
